name: "Amazon ECS Deploy Existing Task definition"
description: "Registers an Amazon ECS task definition, and deploys it to an ECS service. It uses the latest task definition."
branding:
  icon: 'cloud'
  color: 'orange'
author: "Pooria Ghaedi"
inputs:
  IMAGE_TAG:
    description: "Image Tag to be replaced with"
    required: true
  CHART_PATH:
    description: "Path of Helm Chart"
    required: true
# outputs:

runs:
  using: "docker"
  image: "Dockerfile"
